name: mela
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter_countdown_timer: ^4.1.0
  flutter:
    sdk: flutter

  draggable_fab: ^0.1.4
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/arrow_back_longer.png
    - assets/icons/clock.png
    - assets/icons/select_list.png

    - assets/images/exit_image.png
    - assets/images/result_image.png
  fonts:
  - family: Asap
    fonts:
      - asset:   assets/fonts/Asap/Asap-Regular.ttf
      - asset:   assets/fonts/Asap/Asap-SemiBold.ttf
      - asset:   assets/fonts/Asap/Asap-Bold.ttf
      - asset:   assets/fonts/Asap/Asap-ExtraBold.ttf

  - family: Mulish
    fonts:
      - asset: assets/fonts/Mulish/Mulish-Bold.ttf
      - asset: assets/fonts/Mulish/Mulish-Regular.ttf
      - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
      - asset: assets/fonts/Mulish/Mulish-ExtraBold.ttf
