name: mela
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.5.3

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # A
  # another_flushbar: ^1.12.29
  # B
  # C
  cupertino_icons: ^1.0.5
  # D
  draggable_fab: ^0.1.4
  dio: ^5.1.1
  # E
  event_bus: ^2.0.0
  # F
  fl_chart: ^0.69.2
  flutter_mobx: ^2.0.6+5
  flutter_countdown_timer: ^4.1.0
  flutter_secure_storage: ^9.2.2
  flutter_html: ^3.0.0-beta.2
  flutter_math_fork: ^0.7.2
  # G
  get_it: ^7.2.0
  # google_fonts: ^4.0.3
  # H
  http: ^1.2.2
  # I
  intl: ^0.19.0
  image_picker: ^1.0.7
  # J
  json_serializable: ^6.6.1
  # K
  # L
  # M
  mobx: ^2.1.4
  # N
  # O
  # P
  provider: ^6.1.2
  path_provider: ^2.0.14
  pin_code_fields: ^8.0.1
  # Q
  # R
  # S
  syncfusion_flutter_pdfviewer: ^28.1.33
  syncfusion_flutter_core: ^28.1.33
  shared_preferences: ^2.1.0
  sembast_web: ^2.1.3
  sembast: ^3.4.4
  # T
  # U
  # V
  validators: ^3.0.0
  # W
  # X
  xxtea: ^2.1.0
  # Y
  # Z

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.13.1
  mobx_codegen: ^2.2.0
  build_runner: ^2.3.3
  analyzer: ^5.10.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/grades/
    - assets/images/topics/
    - assets/icons/
    - assets/icons/arrow_back_longer.png
    - assets/icons/clock.png
    - assets/icons/select_list.png

    - assets/images/exit_image.png
    - assets/images/result_image.png
    - assets/lang/
  fonts:
  - family: Asap
    fonts:
      - asset:   assets/fonts/Asap/Asap-Regular.ttf
      - asset:   assets/fonts/Asap/Asap-SemiBold.ttf
      - asset:   assets/fonts/Asap/Asap-Bold.ttf
      - asset:   assets/fonts/Asap/Asap-ExtraBold.ttf

  - family: Mulish
    fonts:
      - asset: assets/fonts/Mulish/Mulish-Bold.ttf
      - asset: assets/fonts/Mulish/Mulish-Regular.ttf
      - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
      - asset: assets/fonts/Mulish/Mulish-ExtraBold.ttf
