name: mela
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter_countdown_timer: ^4.1.0
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/topics/
    - assets/icons/
  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap/Asap-Bold.ttf
        - asset: assets/fonts/Asap/Asap-ExtraBold.ttf
        - asset: assets/fonts/Asap/Asap-Regular.ttf
        - asset: assets/fonts/Asap/Asap-SemiBold.ttf

    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-Bold.ttf
        - asset: assets/fonts/Mulish/Mulish-ExtraBold.ttf
        - asset: assets/fonts/Mulish/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf



